apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  ports:
    - name: minio-client-port
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: minio
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: minio
  name: minio
spec:
  containers:
    - args:
        - server
        # - /data
        - /data1
      env:
        - name: MINIO_ACCESS_KEY
          value: AKIAIOSFODNN7EXAMPLE
        - name: MINIO_SECRET_KEY
          value: 1d8e1c1c6427c9da2d3a260f6fb7a123b7d0dffeb87190605e20244b6a8b823f
      # image: quay.io/cloudservices/minio:latest
      image: quay.io/opendatahub/modelmesh-minio-examples:v0.8.0
      name: minio
---
apiVersion: v1
kind: Secret
metadata:
  name: storage-config
stringData:
  localMinIO: |
    {
      "type": "s3",
      "access_key_id": "AKIAIOSFODNN7EXAMPLE",
      "secret_access_key": "1d8e1c1c6427c9da2d3a260f6fb7a123b7d0dffeb87190605e20244b6a8b823f",
      "endpoint_url": "http://minio:9000",
      "default_bucket": "modelmesh-example-models",
      "region": "us-south"
    }

