apiVersion: v1
kind: Secret
metadata:
  name: storage-config
stringData:
  localMinIO: |
    {
      "type": "s3",
      "access_key_id": "<ACCESS_KEY>",
      "secret_access_key": "<SECRET_ACCESS_KEY>",
      "endpoint_url": "https://s3.<region>.amazonaws.com",
      "default_bucket": "<bucket>",
      "region": "<region>"
    }

